apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: dc-cluster-backup
  namespace: postgresdc
spec:
  method: barmanObjectStore
  cluster:
    name: dc-cluster
  target:
    destinationPath: s3://dc-backups-bucket/dc
    credentials:
      accessKeyId:
        value: "access-key123"
      secretAccessKey:
        value: "secret-key123"
    s3:
      endpoint: "http://pg-backup.k8s.local"
      region: "us-east-1"