apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgcluster-dr1
  namespace: dr
spec:
  instances: 3
  storage:
    size: 1Gi
    storageClass: rook-cephfs
  walStorage:
    size: 1Gi
    storageClass: rook-cephfs    
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: backup5 # Name of the snapshot taken from primary cluster 
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
          namespace: postgres3
  

        walStorage:
          name: backup5-wal  # Name of the snapshot for the WAL (Write-Ahead Logs)
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
          namespace: postgres3
  

