
type: postgresql
mode: recovery

recovery:
  method: object_store
  clusterName: "dc-cluster"
  endpointURL: "http://minio-s3.minio.svc.cluster.local:9000"
  provider: s3
  s3:
    region: ""
    bucket: "dc-backups-bucket"
    path: "/dc-cluster"
    accessKey: "console"
    secretKey: "console123"

cluster:
  instances: 1