apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
  namespace: dc
spec:
  instances: 3
  storage:
    size: 1Gi
    storageClass: rook-cephfs
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: backup-example  # Name of the snapshot taken from primary cluster
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

        walStorage:
          name: backup-example  # Name of the snapshot for the WAL (Write-Ahead Logs)
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

  backup:
    volumeSnapshot:
      className: csi-cephfsplugin-snapclass  # Ensure the backup class is properly set
