apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgcluster-dr
  namespace: postgres3
spec:
  instances: 3
  storage:
    size: 1Gi
    storageClass: rook-cephfs
  walStorage:
    size: 1Gi
    storageClass: rook-cephfs    
  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: backup3 # Name of the snapshot taken from primary cluster 
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
  

        walStorage:
          name: backup3  # Name of the snapshot for the WAL (Write-Ahead Logs)
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

