apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: boostrap-demo-cnpg
  namespace: postgresdr
spec:
  instances: 3
  storage:
    storageClass: "rook-cephfs"
    size: 10Gi
  bootstrap:
    recovery:
      source: dc-cluster
  externalClusters:
    # The external cluster definition
    - name: dc-cluster
      barmanObjectStore:
        endpointURL: "http://minio-s3.minio.svc.cluster.local:9000"
        destinationPath: "s3://dc-backups-bucket/dc-cluster" # Include the correct path within the bucket
        s3Credentials:
          accessKeyId:
            name: helm-dc-cluster-backup-s3-creds
            key: SECRET_ACCESS_KEY
          secretAccessKey:
            name: helm-dc-cluster-backup-s3-creds
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8
