nameOverride: "dc-cluster"
fullnameOverride: "dc-cluster"

type: postgresql
version:
  postgresql: "16"
  timescaledb: "2.15"
  postgis: "3.4"

mode: standalone

cluster:
  instances: 3
  imageName: "postgres:16"
  imagePullPolicy: IfNotPresent
  storage:
    size: 8Gi
    storageClass: "fast-storage"
  walStorage:
    enabled: true
    size: 2Gi
    storageClass: "fast-storage"
  resources:
    limits:
      cpu: "1000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: "info"
  affinity:
    topologyKey: topology.kubernetes.io/zone
  monitoring:
    # -- Whether to enable monitoring
    enabled: true
    podMonitor:
      # -- Whether to enable the PodMonitor
      enabled: true
      # --The list of relabelings for the PodMonitor.
      # Applied to samples before scraping.
      relabelings: []
      # -- The list of metric relabelings for the PodMonitor.
      # Applied to samples before ingestion.
      metricRelabelings: []
    prometheusRule:
      # -- Whether to enable the PrometheusRule automated alerts
      enabled: true
      # -- Exclude specified rules
      excludeRules: []
        # - CNPGClusterZoneSpreadWarning
    # -- Whether the default queries should be injected.
    # Set it to true if you don't want to inject default queries into the cluster.
    disableDefaultQueries: false
    # -- Custom Prometheus metrics
    # Will be stored in the ConfigMap
    customQueries: []
     - name: "pg_cache_hit_ratio"
       query: "SELECT current_database() as datname, sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)) as ratio FROM pg_statio_user_tables;"
       metrics:
         - datname:
             usage: "LABEL"
             description: "Name of the database"
         - ratio:
             usage: GAUGE
             description: "Cache hit ratio"
    # -- The list of secrets containing the custom queries
    customQueriesSecret: []
     - name: custom-queries-secret
       key: custom-queries
backups:
  enabled: true
  provider: s3
  s3:
    region: "us-east-1"
    endpoint: "http://pg-backup.k8s.local"
    bucket: "dc-backups-bucket"
    path: "/dc"
    secretKeyRef:
      name: dc-backup-s3-credentials
      key: secretKey
    accessKeyRef:
      name: dc-backup-s3-credentials
      key: accessKey
  retentionPolicy: "30d"




postgresql:
  parameters:
    max_connections: 500
  pg_hba:
    - host all all 10.0.0.0/24 md5

initdb: 
  database: app
  owner: app_user
  postInitSQL:
    - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
