nameOverride: "dc-cluster"
fullnameOverride: "dc-cluster"

type: postgresql
version:
  postgresql: "16"
  timescaledb: "2.15"
  postgis: "3.4"

mode: standalone

cluster:
  instances: 3
  imageName: "postgres:16"
  imagePullPolicy: IfNotPresent
  storage:
    size: 8Gi
    storageClass: "fast-storage"
  walStorage:
    enabled: true
    size: 2Gi
    storageClass: "fast-storage"
  resources:
    limits:
      cpu: "1000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: "info"
  affinity:
    topologyKey: topology.kubernetes.io/zone

backups:
  enabled: true
  provider: s3
  s3:
    region: "us-east-1"
    endpoint: "http://pg-backup.k8s.local"
    bucket: "dc-backups-bucket"
    path: "/dc"
    secretKeyRef:
      name: dc-backup-s3-credentials
      key: secretKey
    accessKeyRef:
      name: dc-backup-s3-credentials
      key: accessKey
  retentionPolicy: "30d"

monitoring:
  enabled: false
  podMonitor:
    enabled: true
    relabelings: []
  prometheusRule:
    enabled: true
    excludeRules: []
    customQueries: []
    customQueriesSecret: []

postgresql:
  parameters:
    max_connections: 500
  pg_hba:
    - host all all 10.0.0.0/24 md5

initdb: 
  database: app
  owner: app_user
  postInitSQL:
    - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
