nameOverride: "dc-cluster"
fullnameOverride: "dc-cluster"

type: postgresql
version:
  postgresql: "16"
  timescaledb: "2.15"
  postgis: "3.4"

mode: standalone

cluster:
  instances: 3
  imageName: "postgres:16"
  imagePullPolicy: IfNotPresent
  storage:
    size: 8Gi
    storageClass: "fast-storage"
  walStorage:
    enabled: true
    size: 2Gi
    storageClass: "fast-storage"
  resources:
    limits:
      cpu: "1000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: "info"
  affinity:
    topologyKey: topology.kubernetes.io/zone

backups:
  enabled: true
  provider: s3
  s3:
    region: "gds"              
    endpoint: "http://pg-backup-rook-ceph.rook-ceph.svc.cluster.local:80"  # object store's endpoint
    bucket: "dc-backups-bucket"     # Object storage bucket name
    path: "/dc"                     # Path inside the bucket for backups
    accessKey: "dc-access-key"      # Access key for Rook-Ceph S3 user
    secretKey: "dc-secret-key"      # Secret key for Rook-Ceph S3 user
  retentionPolicy: "30d"            # Backup retention policy (e.g., 30 days)

monitoring:
  enabled: true
  podMonitor:
    enabled: true
    relabelings: []
  prometheusRule:
    enabled: true
    excludeRules: []

postgresql:
  parameters:
    max_connections: 500
  pg_hba:
    - host all all 10.0.0.0/24 md5

initdb: 
  database: app
  owner: app_user
  postInitSQL:
    - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
